with Ada.Strings.Unbounded;             use Ada.Strings.Unbounded;

function SVG_Bar_Code (
  kind     : Kind_Of_Code;
  bounding : Box;           --  Box in which the bar code should fit
  unit     : String;        --  length unit, for instance "mm" for millimeter
  text     : String         --  Text to encode
)
return String
is
  svg_code : Unbounded_String;
  --
  type SBC is new Bar_Code with null record;
  overriding procedure Filled_Rectangle (bc : SBC; shape : Box) is
  pragma Unreferenced (bc);
  begin
    svg_code := svg_code &
      "    <rect style=""fill:#000000;""" &
      " x="""      & Img (shape.left) & unit & """" &
      " y="""      & Img (shape.bottom) & unit & """" &
      " height=""" & Img (shape.height) & unit & """" &
      " width="""  & Img (shape.width) & unit & """/>" & ASCII.LF;
  end Filled_Rectangle;
  --
  bc : SBC;
begin
  bc.Draw (kind, bounding, text);
  return
    "<svg height=""" & Img (bounding.height) & unit &
      """ width=""" & Img (bounding.width) & unit &
      """ version=""1.1"" xmlns=""http://www.w3.org/2000/svg"">" & ASCII.LF &
    "    <!--  Automatically generated by " & Bar_Codes.title &
    " version " & Bar_Codes.version &
    ", " & Bar_Codes.reference &
    " @ " & Bar_Codes.web &
    "  -->" & ASCII.LF &
    "    <!--  Text to be encoded: [" & Printable (text) &
    "]  -->" & ASCII.LF &
    --  White rectangle as background
    "    <rect height=""100%"" width=""100%"" style=""fill:#FFFFFF""/>" & ASCII.LF &
    To_String (svg_code) &
    "</svg>";
end SVG_Bar_Code;
